# Generated by Django 4.2 on 2026-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('benefits', models.TextField()),
                ('how_to_use', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Link to an image of the herb')),
            ],
        ),
    ]
