# Generated by Django 4.2.27 on 2026-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='preparation_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='remedy',
            field=models.TextField(blank=True),
        ),
    ]
