# Generated by Django 4.2.27 on 2026-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_healthreport_preparation_method_healthreport_remedy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyurvedicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('remedy', models.TextField()),
                ('preparation', models.TextField()),
                ('search_terms', models.CharField(max_length=255)),
            ],
        ),
    ]
