# Generated by Django 4.2.27 on 2026-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_rating_order_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayurvedicplant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
