# Generated by Django 4.2.27 on 2026-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ayurvedicplant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
